# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false # Inserts a blank line between shell prompts

[aws]
style = 'bold #FF9900'
region_aliases.us-west-2 = 'us-w2'

[cmd_duration]
min_time = 5_000

[git_branch]
truncation_length = 8
truncation_symbol = '…'


[package]
format = 'is [$symbol](208)[$version](bold 208) '

[rust]
version_format = 'v${major}.${minor}'

[terraform]
disabled = true
